neutrinoceros/idefix_cli

- CHANGELOG.md
- idefix_cli/commands/_clean.py
- idefix_cli/commands/_run.py
> make idfx run and idfx clean default to cwd

- CHANGELOG.md
- idefix_cli/commands/_clean.py
- idefix_cli/commands/_run.py
> tmp patched files

- CHANGELOG.md
- idefix_cli/_commons.py
- idefix_cli/commands/_stamp.py
This is a subset of #70 that I'll need for a different fix.
> ENH: add preliminary support for cmake via additional globals and functions in idefix_cli._commons module

- README.md
- idefix_cli/_commands/clone.py
- idefix_cli/_commons.py
- DOC: update README.md with public repo url
- BUG: fix a bug in idfx clone where symlinks would be generated to missing files
> BUG: fix a bug in idfx clone where symlinks would be generated to missing files

- idefix_cli/_commands/run.py
> ENH: don't create a temporary inputfile if no edits are required

- idefix_cli/_commands/run.py
> ENH: prioritize checking for executable (or Markefile) over inifile in error message for idfx run

- idefix_cli/_commands/run.py
> ENH: add support for mpirun in idfx run

- CHANGELOG.md
- README.md
- idefix_cli/_commands/clone.py
- tests/conftest.py
- tests/data/OrszagTang3D/README.md
- tests/data/OrszagTang3D/util.py
- tests/test_clone.py
- tests/test_setup.py
> ENH: add support for persistent (configured) arbitrary inclusions in idfx clone

- .github/workflows/ci.yml
- idefix_cli/_commands/clean.py
- idefix_cli/_commons.py
- tests/test_app_structure.py
It's not clear wether Idefix itself is currently compatible with Windows, but I find that some of the bugs I was able to discover by testing on windows are likely to be more general, so adding support for it still has value.
> ENH: add support for Windows

- idefix_cli/_commands/run.py
- idefix_cli/_commands/stamp.py
- idefix_cli/_commons.py
> RFC: minimise size of future public api module

- idefix_cli/_commands/clone.py
- idefix_cli/_commands/conf.py
- idefix_cli/_commands/stamp.py
- idefix_cli/_commons.py
- idefix_cli/_main.py
- pyproject.toml
> RFC: reduce type uncertainty (strict return types)

- idefix_cli/_commands/run.py
> ENH: improve phrasing in compilation prompt

- idefix_cli/_main.py
- pyproject.toml
- TST: treat warnings as errors
- RFC: refactor dynamical command loading to avoid deprecation warnings
>  RFC: refactor dynamical command loading to avoid deprecation warning

- idefix_cli/_commands/conf.py
- idefix_cli/_main.py
- tests/test_ux.py
> BUG: fix idfx conf help message and add defaults to all commands help messages

- docs/plugins.md
> DOC: document how to configure plugins directory

- docs/plugins.md
- docs/requirements.txt
- idefix_cli/_commands/clean.py
- idefix_cli/_commands/clone.py
- idefix_cli/_commands/conf.py
- idefix_cli/_main.py
- idefix_cli/lib.py
- mkdocs.yml
- tests/conftest.py
goal: close #193 
breaking changes: 3 functions renamed
`get_user_configuration` -> `get_configuration`
`get_user_conf_requirement` -> `get_option`
`get_filetree` -> `make_file_tree`
> DOC: document public api idefix_cli.lib

- idefix_cli/_main.py
- idefix_cli/_theme.py
- idefix_cli/lib.py
- pyproject.toml
> ENH: implement alternative command

- idefix_cli/_commands/conf.py
> BUG: fix a used-before-definition error detected by mypy

- pyproject.toml
fix an unreleased bug from #244
> BUG: hotfix CLI install

- CHANGELOG.md
- docs/commands.md
- idefix_cli/_commands/run.py
> DEPR: deprecate --duration parameter in idfx run

- CHANGELOG.md
- idefix_cli/_commands/run.py
- tests/test_run.py
> BUG: fix a bug in idfx run where --times argument would be silently ignored if passed without --one-step

- CHANGELOG.md
- idefix_cli/_commands/run.py
- tests/test_run.py
> BUG: fix a bug where idfx run --times -1 would not stop until tstop was reached

- CHANGELOG.md
- docs/commands.md
- idefix_cli/_commands/switch.py
- tests/test_ux.py
inspired by a question from @volodia99
> ENH: add new command (idfx switch)

- CHANGELOG.md
- docs/commands.md
- idefix_cli/_commands/run.py
- tests/test_run.py
Also provides a better implementation for this mechanism when using idefix >= 1.0
> ENH: improvements to idfx run step-by-step mode

- CHANGELOG.md
- docs/commands.md
> DOC: document how to use ccmake through idfx conf

- CHANGELOG.md
- src/idefix_cli/_commands/digest.py
> ENH: sort log files by process number in idfx digest

- CHANGELOG.md
- src/idefix_cli/_commands/digest.py
- tests/data/log_crash/idefix.0.log
- tests/test_digest.py
> BUG: fix a bug where idfx digest would generate invalid json from logs that end with an inlined warning or an error

- CHANGELOG.md
- docs/commands.md
- src/idefix_cli/_commands/digest.py
- tests/test_digest.py
> ENH: add support for parsing arbitrary files with `idfx digest`

- CHANGELOG.md
- src/idefix_cli/__main__.py
bug originally discovered by @volodia99
> BUG: fix baballe digest > file.json

- CHANGELOG.md
- src/idefix_cli/_commands/digest.py
- tests/test_digest.py
bug originally discovered by @volodia99
> BUG: fix a bug where idfx digest would choke on files where no line is captured

- CHANGELOG.md
> DOC: fix a changelog entry

- .pre-commit-config.yaml
- README.md
- pyproject.toml
- src/idefix_cli/_commands/digest.py
- STY migrate from black to ruff-format
- MNT: autoupdate pre-commit hooks
> STY migrate from black to ruff-format

- src/idefix_cli/_commands/digest.py
> RFC: use strict zipping

- CHANGELOG.md
- src/idefix_cli/_commands/clone.py
- src/idefix_cli/lib.py
- tests/test_clone.py
> ENH (clone): add an `--exclude` argument

- .readthedocs.yaml
quick follow up to #424
see https://readthedocs.org/projects/idefix-cli/builds/26721959/ for the failed build
> DOC: fixup RTD

- pyproject.toml
> BLD: migrate build backend to flit-core
